feat: add developer and decision records links on sidebar
eclipse-edc/docs pull request #83
Opened 2023-08-17 10:32 UTC by ndr-brt

## What this PR changes/adds

Adds `Developer` and `Decision Records` links for every component in the sidebar.
e.g.
![Screenshot_20230817_122833](https://github.com/eclipse-edc/docs/assets/8570990/ee11f0ef-09ff-4342-b085-f2b4070b3e7d)

## Why it does that

Improve browsability.

## Further notes

- converted the _sidebar.md file to pure markdown, it seems to work fine.
- added the [docsify-sidebar-collapse](https://www.npmjs.com/package/docsify-sidebar-collapse) plugin to have a more readable menu

## Linked Issue(s)

Closes #82 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2023-08-18 12:12 UTC, mspiekermann reviewed
Like to have the sub items! But, should we change _Developer_ to _Documentation_, _Docs_ or _Developer Docs_?

2023-08-21 12:39 UTC, ndr-brt commented
> Like to have the sub items! But, should we change _Developer_ to _Documentation_, _Docs_ or _Developer Docs_?

I think that "docs" should be implicit, because this is a documentation site, as we don't have like `Connector docs`, `IdentityHub docs` as well.

2023-08-21 15:49 UTC, paullatzelsperger approved these changes

2023-08-22 07:24 UTC, juliapampus commented
Will take a look

2023-08-22 07:33 UTC, juliapampus requested changes
I know why I did not include this plugin... the design of the sidebar gets even more terrible :')

2023-08-22 07:33 UTC, juliapampus commented on docs/_sidebar.md
> +  - [Developer](/submodule/Connector/docs/developer/)
```suggestion
  - [Documentation](/submodule/Connector/docs/developer/)
```
Would call all of them `Documentation` (or `Developer Documentation`).

2023-08-22 07:33 UTC, juliapampus commented on docs/_sidebar.md
> +  - [Developer](/submodule/Connector/docs/developer/)
Better `Documentation` because we will have `Developer Documentation` in the getting started section.

2023-08-22 07:35 UTC, juliapampus commented
Can we maybe not include the plugin? The sidebar gets collapsed anyways, automatically when another item is selected: 
![image](https://github.com/eclipse-edc/docs/assets/72392527/2d2b3435-8d43-461a-9b84-e8bc1da26032)

2023-08-22 08:24 UTC, ndr-brt commented
> Can we maybe not include the plugin? The sidebar gets collapsed anyways, automatically when another item is selected: ![image](https://user-images.githubusercontent.com/72392527/262270656-2d2b3435-8d43-461a-9b84-e8bc1da26032.png)

I think you just removed the css, because removing also the plugin js script there's no collapse, and it becomes quite unreadable...

![Screenshot_20230822_102400](https://github.com/eclipse-edc/docs/assets/8570990/05f7a97c-75ee-4c2b-9987-b19e4b1cfe3a)

2023-08-22 08:53 UTC, juliapampus commented
> I think you just removed the css, because removing also the plugin js script removed the collapse feature, and it becomes quite unreadable...

True. What about creating an own .css? I adjusted the docsify-sidebar-collapse/dist/sidebar.min.css a little bit (latest commit): 
![image](https://github.com/eclipse-edc/docs/assets/72392527/ef6b1710-0557-47e5-8b88-3b8e9dd1ad8e)

This way, the sidebar is even on the left hand side.

2023-08-22 08:55 UTC, juliapampus approved these changes

2023-08-22 08:56 UTC, juliapampus commented
Feel free to remove that commit. Thought that would be more helpful than posting it here :D @ndr-brt

2023-08-22 09:38 UTC, ndr-brt commented
> Feel free to remove that commit. Thought that would be more helpful than posting the code here :D so you can check locally @ndr-brt

thanks, looks good to me. let's merge!

2023-08-22 09:38 UTC, merged